apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hubhub.fullname" . }}-secrets
data:
  {{- if .Values.containers.password }}
  containers_password: {{ .Values.containers.password | b64enc }}
  {{- end }}
  {{- if .Values.containers.user }}
  containers_user: {{ .Values.containers.user | b64enc }}
  {{- end }}
  {{- if .Values.containers.url }}
  containers_url: {{ .Values.containers.url  | b64enc }}
  {{- end }}
  {{- if .Values.containers.org }}
  containers_org: {{ .Values.containers.org | b64enc }}
  {{- end }}
  {{- if .Values.dockerhub.password }}
  dockerhub_password: {{ .Values.dockerhub.password | b64enc }}
  {{- end }}
  {{- if .Values.dockerhub.user }}
  dockerhub_user: {{ .Values.dockerhub.user | b64enc }}
  {{- end }}
  {{- if .Values.dockerhub.org }}
  dockerhub_org: {{ .Values.dockerhub.org | b64enc }}
  {{- end }}
  {{- if .Values.github.access_token }}
  github_access_token: {{ .Values.github.access_token | b64enc }}
  {{- end }}
  {{- if .Values.github.org }}
  github_org: {{ .Values.github.org | b64enc }}
  {{- end }}
