apiVersion: v1
kind: Service
metadata:
  name: {{ include "hubhub.fullname" . }}
  labels:
    {{- include "hubhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "hubhub.selectorLabels" . | nindent 4 }}
